# Generated by Django 4.2.7 on 2023-11-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
